# Mastering TensorFlow: Day 2 - Setting Up the Environment and First Program


**Importing TensorFlow**

In [9]:
import tensorflow as tf

# Checking TensorFlow version
print("TensorFlow version:", tf.__version__)



TensorFlow version: 2.17.0


**Explanation : In this cell, we’re importing TensorFlow and verifying the installation by printing the version. This ensures that everything is set up correctly before we move on.**

## What are Tensors?
Tensors are the fundamental building blocks of TensorFlow. They are multi-dimensional arrays with a uniform type. Tensors can represent everything from simple numbers (scalars) to complex multidimensional data like images or videos.

- **Scalar:** A single number (0-dimensional tensor).
- **Vector:** A 1-dimensional tensor (like a list of numbers).
- **Matrix:** A 2-dimensional tensor (like a 2D array).
- **n-D Tensor:** A multi-dimensional array.

Let's create some basic tensors.


## What is constant`?
In TensorFlow, `tf.constant` is used to create a tensor with a fixed value. This tensor is immutable, meaning its value cannot be changed after it's created. It's often used for constants or fixed parameters in your models.


In [10]:
# Creating a constant tensor
constant_tensor = tf.constant([1, 2, 3, 4, 5])
print("Constant Tensor:", constant_tensor)

# Creating a 2D constant tensor (matrix)
constant_matrix = tf.constant([[10, 20], [30, 40]])
print("Constant Matrix:\n", constant_matrix)


Constant Tensor: tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
Constant Matrix:
 tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


## What is Variable?
`tf.Variable` is used to create a tensor whose value can be changed. It is mutable and is typically used to store weights, biases, and other parameters in a neural network that need to be updated during training.


In [11]:
# Creating a variable tensor
variable_tensor = tf.Variable([1, 2, 3, 4, 5])
print("Variable Tensor:", variable_tensor)

# Modifying the value of the variable tensor
variable_tensor.assign([5, 4, 3, 2, 1])
print("Modified Variable Tensor:", variable_tensor)


Variable Tensor: <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>
Modified Variable Tensor: <tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([5, 4, 3, 2, 1], dtype=int32)>


## constant vs Variable
- **`tf.constant`:** Immutable tensor, value cannot be changed once created.
- **`tf.Variable`:** Mutable tensor, value can be updated during execution.

Understanding when to use each is key to effective TensorFlow programming. Constants are used for fixed values, while variables are used for parameters that are updated during training.


In [3]:
# Creating a scalar
scalar = tf.constant(7)
print("Scalar:", scalar)

# Creating a vector
vector = tf.constant([10, 20, 30])
print("Vector:", vector)

# Creating a matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:", matrix)

# Creating a tensor
tensor = tf.constant([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Tensor:", tensor)


Scalar: tf.Tensor(7, shape=(), dtype=int32)
Vector: tf.Tensor([10 20 30], shape=(3,), dtype=int32)
Matrix: tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Tensor: tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


**Explanation:
Here, we’re creating different types of tensors: a scalar, a vector, a matrix, and a more complex multi-dimensional tensor. This is fundamental to understanding how TensorFlow represents data.**

**Basic Tensor Operations
text**

In [5]:
# Performing basic operations on tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Element-wise addition
c = tf.add(a, b)
print("Element-wise addition:", c)

# Element-wise multiplication
d = tf.multiply(a, b)
print("Element-wise multiplication:", d)

#Element-wise subtraction
e = tf.subtract(a, b)
print("Element-wise subtraction:", e)

#Element-wise division
f = tf.divide(a, b)
print("Element-wise division:", f)


Element-wise addition: tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Element-wise multiplication: tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Element-wise subtraction: tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
Element-wise division: tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


**Explanation:
In this section, we perform basic tensor operations such as addition,subtraction,multiplication and division. These operations are crucial as they form the basis of more complex neural network operations.**

## Conclusion
Today, we’ve successfully set up our environment, understood the core concept of tensors, and performed some basic operations using TensorFlow. These building blocks will be essential as we move forward into more complex topics.

Tomorrow, we'll explore how to work with data in TensorFlow and start building our first model. Stay tuned, and keep following along on this journey! 🚀
