# Mastering TensorFlow: Day 9 - Data Preprocessing and Augmentation


## Why Data Preprocessing is Important
Before feeding data into a machine learning model, it is crucial to preprocess it to ensure consistency, remove noise, and enhance the model's ability to learn. Today, we will focus on normalization, standardization, and data augmentation techniques.


In [ ]:
import tensorflow as tf
import numpy as np

# Creating a simple dataset
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=np.float32)
labels = np.array([0, 1, 2])

# Converting to TensorFlow Dataset
dataset = tf.data.Dataset.from_tensor_slices((data, labels))

# Normalization function
def normalize(x, y):
    x = x / 9.0  # Normalizing to the range [0, 1]
    return x, y

# Apply normalization
dataset = dataset.map(normalize)

# Viewing the normalized data
for element in dataset:
    print(element)


(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.11111111, 0.22222222, 0.33333334], dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=0>)
(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.44444445, 0.5555556 , 0.6666667 ], dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=1>)
(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.7777778, 0.8888889, 1.       ], dtype=float32)>, <tf.Tensor: shape=(), dtype=int64, numpy=2>)


In [ ]:
# Example of data augmentation (randomly flip and adjust brightness)
def augment(image):
    image = tf.image.random_flip_left_right(image)
    image = tf.image.random_flip_up_down(image)
    image = tf.image.random_brightness(image, max_delta=0.1)
    return image

# Creating a random image dataset for demonstration
image_data = np.random.rand(5, 28, 28, 1).astype('float32')  # Random grayscale images
image_dataset = tf.data.Dataset.from_tensor_slices(image_data)

# Applying augmentation
augmented_dataset = image_dataset.map(augment)

# Displaying the augmented images
for img in augmented_dataset:
    print(img.shape)


(28, 28, 1)
(28, 28, 1)
(28, 28, 1)
(28, 28, 1)
(28, 28, 1)


## Practical Tips for Data Preprocessing and Augmentation
1. **Normalization**: Always normalize your data to ensure consistency.
2. **Augmentation**: Use augmentation to artificially expand your dataset, which can help your model generalize better.
3. **Experimentation**: Try different augmentation techniques to see what works best for your specific dataset.


## Conclusion
Data preprocessing and augmentation are essential steps in preparing your dataset for model training. They help in making the model more robust and capable of generalizing to new data. By combining normalization and augmentation, you can significantly improve your model's performance.
